# Generated by Django 4.1.2 on 2022-10-17 06:42

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='articles/post')),
            ],
        ),
    ]
